owner: benharri
repo: upptime
user-agent: benharri

sites:
  - name: tilde.team
    url: https://tilde.team
  - name: tildegit
    url: https://tildegit.org
  - name: tilde news
    url: https://tilde.news
  - name: tilde chat
    url: https://tilde.chat
  - name: homepage
    url: https://benharr.is
  - name: bsd.tilde.team
    url: https://bsd.tilde.team
  - name: mastodon
    url: https://tilde.zone
  - name: tcpinball
    url: https://tcpinball.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "some uptime checks for my stuff"
  introMessage: This is a status page for ben's stuff
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: uptime.io
      href: https://status.bhh.sh
    - title: infra
      href: https://tilde.wiki/wiki/User:Ben/Servers

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
